name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: test-z
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: z
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Setup Postgres
        run: psql < db/schema.sql
        env:
          PGDATABASE: test-z
          PGHOST: localhost
          PGPASSWORD: postgres
          PGUSER: z

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make all

      - name: Test
        run: make test:ci
        env:
          PGPASSWORD: postgres
